/**
 * Value generator: Order Number.
 *
 * The customer-facing reference of an accepted Order, for example
 * `SO-7K3M9Q2XH4TB`: the prefix `SO-` followed by 12 Crockford base32
 * characters (60 random bits).
 *
 * Why this format:
 *
 * - The `SO-` prefix makes it recognisable and distinct from the Order's UUID
 *   `id` and from the client's `submissionId`.
 * - Crockford base32 (`0-9`, `A-Z` without `I`, `L`, `O`, `U`) is unambiguous
 *   when read aloud or retyped and avoids accidental words.
 * - It is random rather than sequential, so it reveals no order volume or rate
 *   and needs no database sequence, migration or extra round trip.
 * - It is not derived from the UUIDv7 `id`: that would leak the creation time,
 *   and the `id` is generated by the database on insert anyway.
 * - 60 bits give roughly a 1-in-2-million chance of any collision after a
 *   million Orders. The unique `orders_order_number_key` index is the backstop:
 *   the persistence adapter reports its violation as a transient failure, and
 *   SubmitOrder retries with a new number within its bounded attempts.
 *
 * Randomness comes from Web Crypto (`globalThis.crypto.getRandomValues`), so
 * core needs no `node:` import.
 *
 * @see docs/architecture.md, "Domain model"
 * @module
 */

/** Crockford base32 alphabet: digits and upper-case letters without I, L, O, U. */
const CROCKFORD_BASE32 = "0123456789ABCDEFGHJKMNPQRSTVWXYZ";

/** Number of random base32 characters after the prefix (12 x 5 = 60 bits). */
const ORDER_NUMBER_LENGTH = 12;

/** `SO-` followed by 12 upper-case Crockford base32 characters. */
export const ORDER_NUMBER_PATTERN = /^SO-[0-9A-HJKMNP-TV-Z]{12}$/;

/**
 * Generates a new random Order Number matching {@link ORDER_NUMBER_PATTERN}.
 *
 * Each character takes the low 5 bits of one random byte; 256 is a multiple of
 * 32, so every character is uniformly distributed.
 */
export function generateOrderNumber(): string {
  const bytes = globalThis.crypto.getRandomValues(new Uint8Array(ORDER_NUMBER_LENGTH));
  let suffix = "";
  for (const byte of bytes) {
    suffix += CROCKFORD_BASE32[byte & 0b11111];
  }
  return `SO-${suffix}`;
}
