-- Initial SCOS Ordering schema.
--
-- Table, index, and foreign-key DDL was generated by
-- `prisma migrate diff --from-empty --to-schema prisma/schema.prisma --script`.
-- The created_at/updated_at DEFAULT NOW() clauses are hand-written: the Prisma
-- schema declares them as @default(dbgenerated()) so the client never sends
-- its own clock value. The sections after the generated DDL are hand-written
-- because Prisma cannot express them: CHECK constraints, the shared timestamp
-- trigger function and per-table triggers (ADR 0003), and lookup values.
-- See docs/database-schema.md.

-- CreateSchema
CREATE SCHEMA IF NOT EXISTS "public";

-- CreateTable
CREATE TABLE "submission_outcome" (
    "value" TEXT NOT NULL,
    "description" TEXT,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT NOW(),
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT NOW(),

    CONSTRAINT "submission_outcome_pkey" PRIMARY KEY ("value")
);

-- CreateTable
CREATE TABLE "rejection_reason" (
    "value" TEXT NOT NULL,
    "description" TEXT,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT NOW(),
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT NOW(),

    CONSTRAINT "rejection_reason_pkey" PRIMARY KEY ("value")
);

-- CreateTable
CREATE TABLE "warehouse" (
    "id" UUID NOT NULL DEFAULT uuidv7(),
    "name" TEXT NOT NULL,
    "latitude" DOUBLE PRECISION NOT NULL,
    "longitude" DOUBLE PRECISION NOT NULL,
    "stock" INTEGER NOT NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT NOW(),
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT NOW(),

    CONSTRAINT "warehouse_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "submission" (
    "id" UUID NOT NULL DEFAULT uuidv7(),
    "submission_key" TEXT NOT NULL,
    "quantity" INTEGER NOT NULL,
    "destination_latitude" DOUBLE PRECISION NOT NULL,
    "destination_longitude" DOUBLE PRECISION NOT NULL,
    "outcome" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT NOW(),
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT NOW(),

    CONSTRAINT "submission_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "customer_order" (
    "id" UUID NOT NULL DEFAULT uuidv7(),
    "order_number" TEXT NOT NULL,
    "submission_id" UUID NOT NULL,
    "submission_outcome" TEXT NOT NULL DEFAULT 'ACCEPTED',
    "unit_price" DECIMAL(12,2) NOT NULL,
    "merchandise_subtotal" DECIMAL(12,2) NOT NULL,
    "discount_rate" DECIMAL(5,4) NOT NULL,
    "discount_amount" DECIMAL(12,2) NOT NULL,
    "discounted_merchandise_total" DECIMAL(12,2) NOT NULL,
    "shipping_cost" DECIMAL(12,2) NOT NULL,
    "order_total" DECIMAL(12,2) NOT NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT NOW(),
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT NOW(),

    CONSTRAINT "customer_order_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "order_allocation" (
    "id" UUID NOT NULL DEFAULT uuidv7(),
    "order_id" UUID NOT NULL,
    "warehouse_id" UUID NOT NULL,
    "quantity" INTEGER NOT NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT NOW(),
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT NOW(),

    CONSTRAINT "order_allocation_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "submission_rejection" (
    "submission_id" UUID NOT NULL,
    "submission_outcome" TEXT NOT NULL DEFAULT 'REJECTED',
    "reason" TEXT NOT NULL,
    "unit_price" DECIMAL(12,2) NOT NULL,
    "merchandise_subtotal" DECIMAL(12,2) NOT NULL,
    "discount_rate" DECIMAL(5,4) NOT NULL,
    "discount_amount" DECIMAL(12,2) NOT NULL,
    "discounted_merchandise_total" DECIMAL(12,2) NOT NULL,
    "shipping_cost" DECIMAL(12,2),
    "order_total" DECIMAL(12,2),
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT NOW(),
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT NOW(),

    CONSTRAINT "submission_rejection_pkey" PRIMARY KEY ("submission_id")
);

-- CreateIndex
CREATE UNIQUE INDEX "warehouse_name_key" ON "warehouse"("name");

-- CreateIndex
CREATE UNIQUE INDEX "submission_submission_key_key" ON "submission"("submission_key");

-- CreateIndex
CREATE UNIQUE INDEX "submission_id_outcome_key" ON "submission"("id", "outcome");

-- CreateIndex
CREATE UNIQUE INDEX "customer_order_order_number_key" ON "customer_order"("order_number");

-- CreateIndex
CREATE UNIQUE INDEX "customer_order_submission_id_key" ON "customer_order"("submission_id");

-- CreateIndex
CREATE UNIQUE INDEX "customer_order_submission_id_outcome_key" ON "customer_order"("submission_id", "submission_outcome");

-- CreateIndex
CREATE INDEX "order_allocation_warehouse_id_idx" ON "order_allocation"("warehouse_id");

-- CreateIndex
CREATE UNIQUE INDEX "order_allocation_order_id_warehouse_id_key" ON "order_allocation"("order_id", "warehouse_id");

-- CreateIndex
CREATE INDEX "submission_rejection_reason_idx" ON "submission_rejection"("reason");

-- CreateIndex
CREATE UNIQUE INDEX "submission_rejection_submission_id_outcome_key" ON "submission_rejection"("submission_id", "submission_outcome");

-- AddForeignKey
ALTER TABLE "submission" ADD CONSTRAINT "submission_outcome_fkey" FOREIGN KEY ("outcome") REFERENCES "submission_outcome"("value") ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE "customer_order" ADD CONSTRAINT "customer_order_submission_fkey" FOREIGN KEY ("submission_id", "submission_outcome") REFERENCES "submission"("id", "outcome") ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE "order_allocation" ADD CONSTRAINT "order_allocation_order_id_fkey" FOREIGN KEY ("order_id") REFERENCES "customer_order"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE "order_allocation" ADD CONSTRAINT "order_allocation_warehouse_id_fkey" FOREIGN KEY ("warehouse_id") REFERENCES "warehouse"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE "submission_rejection" ADD CONSTRAINT "submission_rejection_submission_fkey" FOREIGN KEY ("submission_id", "submission_outcome") REFERENCES "submission"("id", "outcome") ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE "submission_rejection" ADD CONSTRAINT "submission_rejection_reason_fkey" FOREIGN KEY ("reason") REFERENCES "rejection_reason"("value") ON DELETE RESTRICT ON UPDATE RESTRICT;


-- ---------------------------------------------------------------------------
-- CHECK constraints (not expressible in the Prisma schema)
-- ---------------------------------------------------------------------------

ALTER TABLE "submission_outcome"
    ADD CONSTRAINT "submission_outcome_value_check" CHECK ("value" ~ '^[A-Z][A-Z0-9_]*$');

ALTER TABLE "rejection_reason"
    ADD CONSTRAINT "rejection_reason_value_check" CHECK ("value" ~ '^[A-Z][A-Z0-9_]*$');

ALTER TABLE "warehouse"
    ADD CONSTRAINT "warehouse_name_check" CHECK (btrim("name") <> ''),
    ADD CONSTRAINT "warehouse_latitude_check" CHECK ("latitude" BETWEEN -90 AND 90),
    ADD CONSTRAINT "warehouse_longitude_check" CHECK ("longitude" BETWEEN -180 AND 180),
    ADD CONSTRAINT "warehouse_stock_check" CHECK ("stock" >= 0);

ALTER TABLE "submission"
    ADD CONSTRAINT "submission_submission_key_check"
        CHECK (btrim("submission_key") <> '' AND char_length("submission_key") <= 255),
    ADD CONSTRAINT "submission_quantity_check" CHECK ("quantity" > 0),
    ADD CONSTRAINT "submission_destination_latitude_check"
        CHECK ("destination_latitude" BETWEEN -90 AND 90),
    ADD CONSTRAINT "submission_destination_longitude_check"
        CHECK ("destination_longitude" BETWEEN -180 AND 180);

-- An Order may only reference an ACCEPTED submission (via the composite
-- foreign key on submission_id, submission_outcome).
ALTER TABLE "customer_order"
    ADD CONSTRAINT "customer_order_order_number_check" CHECK (btrim("order_number") <> ''),
    ADD CONSTRAINT "customer_order_submission_outcome_check"
        CHECK ("submission_outcome" = 'ACCEPTED'),
    ADD CONSTRAINT "customer_order_unit_price_check" CHECK ("unit_price" >= 0),
    ADD CONSTRAINT "customer_order_merchandise_subtotal_check" CHECK ("merchandise_subtotal" >= 0),
    ADD CONSTRAINT "customer_order_discount_rate_check" CHECK ("discount_rate" BETWEEN 0 AND 1),
    ADD CONSTRAINT "customer_order_discount_amount_check" CHECK ("discount_amount" >= 0),
    ADD CONSTRAINT "customer_order_discounted_merchandise_total_check"
        CHECK ("discounted_merchandise_total" >= 0
            AND "discounted_merchandise_total" = "merchandise_subtotal" - "discount_amount"),
    ADD CONSTRAINT "customer_order_shipping_cost_check" CHECK ("shipping_cost" >= 0),
    ADD CONSTRAINT "customer_order_order_total_check"
        CHECK ("order_total" >= 0
            AND "order_total" = "discounted_merchandise_total" + "shipping_cost");

ALTER TABLE "order_allocation"
    ADD CONSTRAINT "order_allocation_quantity_check" CHECK ("quantity" > 0);

-- A rejection may only reference a REJECTED submission. Insufficient stock
-- has no shipping plan, so shipping and total are absent; an excessive
-- shipping rejection records both. A new reason requires updating this CHECK.
ALTER TABLE "submission_rejection"
    ADD CONSTRAINT "submission_rejection_submission_outcome_check"
        CHECK ("submission_outcome" = 'REJECTED'),
    ADD CONSTRAINT "submission_rejection_unit_price_check" CHECK ("unit_price" >= 0),
    ADD CONSTRAINT "submission_rejection_merchandise_subtotal_check"
        CHECK ("merchandise_subtotal" >= 0),
    ADD CONSTRAINT "submission_rejection_discount_rate_check"
        CHECK ("discount_rate" BETWEEN 0 AND 1),
    ADD CONSTRAINT "submission_rejection_discount_amount_check" CHECK ("discount_amount" >= 0),
    ADD CONSTRAINT "submission_rejection_discounted_merchandise_total_check"
        CHECK ("discounted_merchandise_total" >= 0
            AND "discounted_merchandise_total" = "merchandise_subtotal" - "discount_amount"),
    ADD CONSTRAINT "submission_rejection_shipping_cost_check"
        CHECK ("shipping_cost" IS NULL OR "shipping_cost" >= 0),
    ADD CONSTRAINT "submission_rejection_order_total_check"
        CHECK ("order_total" IS NULL
            OR ("order_total" >= 0
                AND "order_total" = "discounted_merchandise_total" + "shipping_cost")),
    ADD CONSTRAINT "submission_rejection_reason_amounts_check"
        CHECK (("reason" = 'INSUFFICIENT_STOCK'
                AND "shipping_cost" IS NULL AND "order_total" IS NULL)
            OR ("reason" = 'SHIPPING_EXCEEDS_LIMIT'
                AND "shipping_cost" IS NOT NULL AND "order_total" IS NOT NULL));

-- ---------------------------------------------------------------------------
-- Database-managed timestamps (ADR 0003)
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.update_timestamp()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS update_submission_outcome_updated_at ON "submission_outcome";
CREATE TRIGGER update_submission_outcome_updated_at
BEFORE UPDATE ON "submission_outcome"
FOR EACH ROW
EXECUTE FUNCTION public.update_timestamp();

DROP TRIGGER IF EXISTS update_rejection_reason_updated_at ON "rejection_reason";
CREATE TRIGGER update_rejection_reason_updated_at
BEFORE UPDATE ON "rejection_reason"
FOR EACH ROW
EXECUTE FUNCTION public.update_timestamp();

DROP TRIGGER IF EXISTS update_warehouse_updated_at ON "warehouse";
CREATE TRIGGER update_warehouse_updated_at
BEFORE UPDATE ON "warehouse"
FOR EACH ROW
EXECUTE FUNCTION public.update_timestamp();

DROP TRIGGER IF EXISTS update_submission_updated_at ON "submission";
CREATE TRIGGER update_submission_updated_at
BEFORE UPDATE ON "submission"
FOR EACH ROW
EXECUTE FUNCTION public.update_timestamp();

DROP TRIGGER IF EXISTS update_customer_order_updated_at ON "customer_order";
CREATE TRIGGER update_customer_order_updated_at
BEFORE UPDATE ON "customer_order"
FOR EACH ROW
EXECUTE FUNCTION public.update_timestamp();

DROP TRIGGER IF EXISTS update_order_allocation_updated_at ON "order_allocation";
CREATE TRIGGER update_order_allocation_updated_at
BEFORE UPDATE ON "order_allocation"
FOR EACH ROW
EXECUTE FUNCTION public.update_timestamp();

DROP TRIGGER IF EXISTS update_submission_rejection_updated_at ON "submission_rejection";
CREATE TRIGGER update_submission_rejection_updated_at
BEFORE UPDATE ON "submission_rejection"
FOR EACH ROW
EXECUTE FUNCTION public.update_timestamp();

-- ---------------------------------------------------------------------------
-- Lookup values (maintained by migrations, not development seeds)
-- ---------------------------------------------------------------------------

INSERT INTO "submission_outcome" ("value", "description") VALUES
    ('ACCEPTED', 'The submission was accepted and created an Order.'),
    ('REJECTED', 'The submission was a business rejection; no Order was created.');

INSERT INTO "rejection_reason" ("value", "description") VALUES
    ('INSUFFICIENT_STOCK', 'Total available warehouse inventory cannot fulfill the requested quantity.'),
    ('SHIPPING_EXCEEDS_LIMIT', 'Shipping cost exceeds 15% of the discounted merchandise total.');
