import { copyFile, mkdir } from "node:fs/promises";

import { type UserConfig, defineConfig } from "tsdown";

const runtimeDependencies = ["@prisma/adapter-pg", "@prisma/client", "@scos/core", "pg"];

/** The Cloudflare Workers client generated by the `workerd` generator in schema.prisma. */
const WORKERD_CLIENT = "src/generated/prisma-workerd";
const QUERY_COMPILER_WASM = "query_compiler_fast_bg.wasm";

// @scos/persistence is bundled with tsdown. The generated Prisma client
// (src/generated/prisma) is bundled; runtime dependencies stay external and
// Prisma's query compiler is loaded from @prisma/client at run time.
const node: UserConfig = {
  entry: {
    index: "src/index.ts",
    database: "src/database.ts",
    "bin/seed": "src/bin/seed.ts",
    "bin/confirm-reset": "src/bin/confirm-reset.ts",
  },
  outDir: "dist",
  // The workerd build below owns dist/workerd; both builds run concurrently.
  clean: ["dist/*", "!dist/workerd"],
  format: "esm",
  platform: "node",
  target: "node24",
  tsconfig: "tsconfig.json",
  // Keep .js/.d.ts names so package.json exports and db:* scripts stay stable.
  fixedExtension: false,
  sourcemap: true,
  // TypeScript 7 is installed, so declarations are generated with tsgo from
  // tsconfig.json. Only the public entries need declarations.
  dts: {
    generator: "tsgo",
    entry: ["src/index.ts", "src/database.ts"],
  },
  deps: {
    // Fail the build if the output imports anything besides these packages
    // (and Node built-ins).
    onlyImport: runtimeDependencies,
  },
};

// The same public API for Cloudflare Workers (package.json "exports", the
// "workerd" condition that Wrangler and @cloudflare/vitest-pool-workers
// resolve). Identical sources, except that every import of the Node.js
// client (./generated/prisma/client) is redirected to the workerd client, so
// the adapters' `Prisma.PrismaClientKnownRequestError`, `Prisma.Decimal` and
// isolation levels come from the same runtime as the client that throws and
// returns them. Prisma's query compiler stays a separate `.wasm` module next
// to the output: workerd cannot compile WebAssembly from bytes at run time,
// so the Worker bundler (Wrangler) imports it as a compiled module.
const workerd: UserConfig = {
  entry: { index: "src/index.ts" },
  outDir: "dist/workerd",
  format: "esm",
  platform: "neutral",
  target: "es2024",
  tsconfig: "tsconfig.json",
  fixedExtension: false,
  sourcemap: true,
  dts: false,
  deps: {
    onlyImport: [...runtimeDependencies, `./${QUERY_COMPILER_WASM}?module`],
  },
  plugins: [
    {
      name: "scos:prisma-workerd-client",
      resolveId(source: string, importer: string | undefined) {
        if (source.endsWith(`${QUERY_COMPILER_WASM}?module`)) {
          return { id: `./${QUERY_COMPILER_WASM}?module`, external: true };
        }
        if (importer !== undefined && /\/generated\/prisma\/client(?:\.js)?$/.test(source)) {
          return this.resolve(
            source.replace(
              /generated\/prisma\/client(?:\.js)?$/,
              "generated/prisma-workerd/client.ts",
            ),
            importer,
          );
        }
        return null;
      },
    },
  ],
  hooks: {
    async "build:done"() {
      await mkdir("dist/workerd", { recursive: true });
      await copyFile(
        `${WORKERD_CLIENT}/internal/${QUERY_COMPILER_WASM}`,
        `dist/workerd/${QUERY_COMPILER_WASM}`,
      );
    },
  },
};

export default defineConfig([node, workerd]);
