/**
 * The OpenAPI 3.1 document, generated by hono-openapi from the Hono app
 * itself: each endpoint app documents its route with its contract
 * (`describeRoute`, `http/describe-route.ts`), and hono-openapi's
 * `generateSpecs` collects them. This module holds only the document-level
 * options: `info`, relative `servers`, `tags`, the reusable 404 response, the
 * documentation routes to leave out, and no default validation error (every
 * route documents its own 400).
 *
 * Deterministic: it reads no environment, opens no connection and adds no
 * timestamps, so `GET /openapi.json` and the offline export
 * (`docs/openapi.json`, `offline.ts`) are the same bytes.
 *
 * @module
 */

import type { Hono } from "hono";
import { type GenerateSpecOptions, generateSpecs } from "hono-openapi";

import { responseOption } from "../http/describe-route";
import { API_PREFIX, SUBMISSION_ADR_URL, notFoundResponse } from "../http/route-contract";

export const OPENAPI_PATH = "/openapi.json";
export const DOCS_PATH = "/docs";

export type JsonObject = { [key: string]: unknown };

/** The generated document. Parts are plain JSON; see the OpenAPI 3.1 specification. */
export interface OpenApiDocument {
  readonly openapi: "3.1.0";
  readonly info: JsonObject;
  readonly servers: readonly JsonObject[];
  readonly tags: readonly JsonObject[];
  readonly paths: Readonly<Record<string, Record<string, JsonObject>>>;
  readonly components: {
    readonly schemas: Readonly<Record<string, JsonObject>>;
    readonly responses: Readonly<Record<string, JsonObject>>;
  };
}

export const API_DESCRIPTION = [
  "Verify and submit orders for the SCOS device against current Warehouse Inventory.",
  [
    "- Request and response bodies are JSON. Requests must be sent with `Content-Type: application/json`; unknown fields are rejected and strings are never coerced to numbers.",
    '- Money is a decimal string with exactly two fractional digits, such as `"150.00"`; `discountRate` is a two-decimal string such as `"0.05"`. `distanceKm` is an unrounded number.',
    "- Every non-2xx body has an `error` object with a machine-readable `code` and a `message`. Most are exactly `ErrorResponse`; a `422` submission rejection (`RejectedSubmission`) also carries the `estimate` that caused it. Any method or path not listed here is `404 NOT_FOUND` (see `components.responses.NotFound`); the unversioned `/orders` paths are not aliases.",
    `- \`POST ${API_PREFIX}/orders\` is deduplicated by the client's \`submissionId\` ([ADR 0004](${SUBMISSION_ADR_URL})).`,
  ].join("\n"),
  "The request examples produce the documented responses against a freshly seeded database when sent in the documented order (the accepted submission before its repeat and the conflicting reuse). After other orders have been accepted, stock differs, so allocations, amounts and outcomes can differ too.",
].join("\n\n");

/**
 * hono-openapi's options, as a fresh object per call so no generation can
 * observe another's. (The library copies `components` shallowly before
 * resolving the `NotFound` schema and does not mutate these options.)
 */
export function openApiOptions(): Partial<GenerateSpecOptions> {
  return {
    documentation: {
      openapi: "3.1.0",
      info: { title: "SCOS Ordering API", version: "1.0.0", description: API_DESCRIPTION },
      servers: [{ url: "/", description: "The server that serves this document." }],
      tags: [
        { name: "Orders", description: "Order verification and submission." },
        { name: "Health", description: "Liveness." },
      ],
      // Empty: generated paths are merged in here, keeping `paths` before `components`.
      paths: {},
      components: { responses: { NotFound: responseOption(notFoundResponse) } },
    },
    exclude: [OPENAPI_PATH, DOCS_PATH],
    // Every route with a body documents its own 400 (the error envelope).
    defaultValidationErrorResponse: false,
  };
}

/** The document of every route `app` documents. */
export async function generateOpenApiDocument(app: Hono): Promise<OpenApiDocument> {
  return (await generateSpecs(app, openApiOptions())) as unknown as OpenApiDocument;
}

/**
 * The document exactly as exported to `docs/openapi.json` and served at
 * `GET /openapi.json`: two-space indentation and a trailing newline.
 */
export function serializeOpenApiDocument(document: OpenApiDocument): string {
  return `${JSON.stringify(document, null, 2)}\n`;
}
